(function(){
 'use strict';
 window.HBMExtensions=window.HBMExtensions||[];
 const lesson=(title,body)=>`<article class="lesson"><h3>${title}</h3>${body}</article>`;
 const paragraph=text=>`<p>${text}</p>`;
 const source=(href,label)=>`<p class="source-note">원문 읽기 · <a href="${href}" target="_blank" rel="noopener">${label} ↗</a></p>`;
 window.HBMExtensions.push({chapters:[
  ['dataflow','GPU 안의 데이터 이동','HBM에 가기 전에, 다시 쓸 수 있을까?','HBM은 GPU 밖에 있는 큰 데이터 저장소입니다. GPU 내부의 레지스터·공유 메모리·캐시를 잘 활용하면 같은 데이터를 반복해서 HBM에서 가져오는 일을 줄일 수 있습니다. 연산을 빠르게 만드는 방법에는 더 넓은 메모리뿐 아니라 덜 옮기는 설계도 있습니다.'],
  ['design','설계 종합 실험','대역폭·용량·열을 동시에 맞춰 보기','한 가지 숫자가 가장 큰 설계가 항상 좋은 설계는 아닙니다. 스택 수는 용량과 전체 대역폭을 함께 늘리지만 소비전력과 패키징 부담도 커질 수 있습니다. 제품 조건과 워크로드 조건을 분리하고, 어떤 제한이 먼저 걸리는지 확인하세요.']
 ],init(api){
  const {$,num,cards,range,select,result,lab,wire,v,read,svg,bars}=api;
  $('body-dataflow').innerHTML=cards([
   ['Register · 레지스터','스레드가 가까이 쓰는 작은 저장소. 부족하면 데이터가 다른 메모리 경로로 밀려날 수 있으며 무조건 많이 쓴다고 좋은 것은 아닙니다.'],
   ['Shared memory / L1','연산 블록 안의 데이터 재사용에 중요한 내부 자원. 공유 메모리의 bank conflict와 HBM의 bank conflict는 다른 계층의 문제입니다.'],
   ['L2 → HBM','여러 연산 유닛이 공유하는 L2에서 데이터를 재사용할 수 있습니다. L2 miss가 발생하면 외부 메모리로 요청이 이어집니다.']
  ])+lesson('읽기 요청을 따라가는 순서',paragraph('① 연산 유닛이 데이터를 요청합니다. ② 캐시에 있으면 가까운 경로에서 제공합니다. ③ 없으면 메모리 컨트롤러가 주소를 해석하고 명령을 스케줄링합니다. ④ PHY가 전기 신호를 송수신하고, 패키지 배선과 HBM 내부 연결을 통해 데이터가 이동합니다. ⑤ 응답이 돌아온 뒤 연산을 계속합니다.')+paragraph('컨트롤러는 언제 어떤 명령을 내릴지 결정하는 디지털 제어 쪽이고, PHY는 데이터를 실제 핀의 신호로 주고받는 인터페이스 쪽입니다. TSV는 HBM 스택 내부 수직 연결, 인터포저는 패키지 안의 수평 연결입니다. 이 세 가지를 같은 부품으로 생각하면 원인 분석을 잘못 시작할 수 있습니다.'))+
   lab('24','데이터 패킷의 여행',select('advs-path','읽기 경로',[['miss','HBM까지 읽기 · L2 miss'],['hit','L2에서 재사용 · hit']])+`<div class="sim-buttons"><button id="advs-send">패킷 보내기 ▶</button><button id="advs-step">한 단계 이동 →</button><button id="advs-reset">처음으로</button></div>`+result('advs-flow-read'),'경로를 이해하기 위한 논리 도해입니다. 각 단계의 화면 이동 시간은 실제 지연시간과 무관하며 GPU의 모든 내부 경로를 표현하지 않습니다.','L2 hit 경로와 miss 경로를 번갈아 선택해 보세요. 어떤 연결을 지나지 않아도 되나요?')+
   lesson('타일링: 한 번 가져와 여러 번 연산',paragraph('행렬 연산에서 작은 타일을 내부 저장소에 올리고 반복 사용하면 HBM 왕복을 줄일 수 있습니다. 요청한 총 byte와 HBM에서 실제 전송한 byte가 같지 않을 수 있는 이유입니다. 캐시 hit rate가 높아도 필수 데이터가 많으면 HBM 트래픽은 여전히 클 수 있습니다.')+paragraph('성능 보고서에서는 연산 집약도를 어느 계층의 byte로 나눴는지도 확인합니다. HBM byte를 기준으로 계산한 집약도와 L1에서 처리한 byte를 기준으로 계산한 값은 다릅니다. FLOP 수는 정밀도와 연산 종류가 일치하는 조건으로 비교해야 합니다.'))+
   lab('25','데이터 재사용과 HBM 트래픽',range('advs-unique','고유 입력 데이터',1,128,16,1,' MB')+range('advs-reuse','같은 데이터 사용 횟수',1,16,8,1,'회')+range('advs-hit','추가 사용의 캐시 적중률',0,100,80,5,'%')+range('advs-ops','전체 연산 수',1,100,20,1,' GFLOP')+result('advs-reuse-read'),'첫 접근은 반드시 HBM에서 가져오고, 두 번째 이후의 접근 중 지정한 비율만 캐시 hit를 가정합니다. writeback·프리페치·캐시 용량·압축은 생략합니다.','적중률을 0%와 100%로 바꿔 보세요. 100% hit에서도 최초 입력 트래픽이 남는 이유는 무엇인가요?')+
   '<div class="formula">HBM MB = 고유 데이터 MB × [1 + (사용 횟수 − 1) × (1 − 추가 접근 hit rate)]<br>HBM 기준 집약도 = GFLOP × 1000 ÷ HBM MB</div>'+
   '<div class="task"><b>프로파일링 체크</b> 실행시간 → 연산량/정밀도 → HBM read/write byte → 캐시 hit/miss → 명령·동시 요청 → 병목 가설 순서로 확인하세요. 이용률 수치 하나만으로 원인을 단정하지 않습니다.</div>'+
   source('https://docs.nvidia.com/nsight-compute/ProfilingGuide/','NVIDIA Nsight Compute · 메모리 계층과 지표')+source('https://developer.nvidia.com/blog/accelerating-hpc-applications-with-nsight-compute-roofline-analysis/','NVIDIA · 계층별 Roofline 해석');
  const flowNodes=[{x:40,y:55,w:120,t:'SM / 연산'},{x:205,y:55,w:100,t:'L2 cache'},{x:350,y:55,w:145,t:'Controller'},{x:350,y:155,w:145,t:'PHY'},{x:205,y:155,w:100,t:'패키지 배선'},{x:40,y:155,w:120,t:'HBM / TSV'}];
  const descriptions=['연산 유닛에서 데이터 읽기 요청','L2 캐시에 데이터가 있는지 확인','메모리 컨트롤러가 주소와 명령을 처리','PHY가 전기적 데이터 신호를 송수신','인터포저 등 패키지 배선을 지나 이동','HBM 내부에서 데이터를 읽고 TSV 경로를 이용','응답 데이터가 돌아와 연산 재개'];
  const returnDescriptions=['응답 데이터를 받아 연산 재개','응답 데이터를 L2 캐시에 채우고 연산 유닛으로 전달','메모리 컨트롤러가 응답 데이터를 내부 경로로 전달','PHY가 HBM에서 돌아온 전기 신호를 수신','읽은 데이터가 패키지 배선을 통해 돌아옴'];
  let flowStep=0,flowTimer=null;
  const flowRoute=()=> $('advs-path').value==='hit'?[0,1,0]:[0,1,2,3,4,5,4,3,2,1,0];
  function stopFlow(){if(flowTimer){clearInterval(flowTimer);flowTimer=null}$('advs-send').textContent='패킷 보내기 ▶'}
  function drawFlow(){const route=flowRoute(),node=flowNodes[route[flowStep]],done=flowStep===route.length-1,returning=$('advs-path').value==='miss'&&flowStep>5;read('advs-flow-read',done?'요청 완료':`${flowStep+1} / ${route.length} 단계`,done?'응답이 돌아왔습니다. 같은 데이터를 다시 쓰는 방법을 생각해 보세요.':(returning?returnDescriptions[route[flowStep]]:descriptions[route[flowStep]]));$('viz-24').innerHTML=svg(`<path d="M160 83h45M305 83h45M420 108v47M350 183h-45M205 183h-45" fill="none" stroke="#94b5a5" stroke-width="2" stroke-dasharray="5"/>`+flowNodes.map((n,i)=>`<rect x="${n.x}" y="${n.y}" width="${n.w}" height="56" rx="9" fill="${i===route[flowStep]?'#ccf292':'#d9e8da'}" stroke="#5f8b78"/><text x="${n.x+12}" y="${n.y+32}">${n.t}</text>`).join('')+`<circle class="flow-packet" cx="${node.x+node.w/2}" cy="${node.y-13}" r="8" fill="#c26335"/><text x="40" y="263" class="label">${$('advs-path').value==='hit'?'L2에서 응답 · HBM 접근 생략':'주황 패킷을 따라 요청 → 메모리 → 응답을 관찰하세요'}</text>`)}
  const advance=()=>{flowStep=Math.min(flowStep+1,flowRoute().length-1);drawFlow();if(flowStep===flowRoute().length-1)stopFlow()};
  $('advs-send').onclick=()=>{if(flowTimer){stopFlow();return}flowStep=0;drawFlow();if(matchMedia('(prefers-reduced-motion: reduce)').matches){$('advs-flow-read').querySelector('p').textContent='동작 줄이기 설정이 켜져 있습니다. 한 단계 이동 버튼으로 관찰하세요.';return}flowTimer=setInterval(advance,600);$('advs-send').textContent='재생 멈추기 ■'};
  $('advs-step').onclick=()=>{stopFlow();if(flowStep===flowRoute().length-1)flowStep=0;else advance();drawFlow()};$('advs-reset').onclick=()=>{stopFlow();flowStep=0;drawFlow()};$('advs-path').oninput=()=>{stopFlow();flowStep=0;drawFlow()};drawFlow();
  const flowObserver=new IntersectionObserver(es=>{if(!es[0].isIntersecting)stopFlow()});flowObserver.observe($('viz-24'));document.addEventListener('visibilitychange',()=>{if(document.hidden)stopFlow()});
  wire(['advs-unique','advs-reuse','advs-hit','advs-ops'],()=>{let unique=v('advs-unique'),count=v('advs-reuse'),hit=v('advs-hit')/100,traffic=unique*(1+(count-1)*(1-hit)),ai=v('advs-ops')*1000/traffic;read('advs-reuse-read',num(traffic,2)+' MB',`HBM 전송량 · 재사용 없을 때 ${unique*count} MB · 집약도 ${num(ai,1)} FLOP/byte`);$('viz-25').innerHTML=bars([['재사용 없음 · HBM MB',unique*count],['현재 · HBM MB',traffic,'#89b753'],['최소 입력 · MB',unique,'#c26335']])});
  $('body-design').innerHTML=lesson('먼저 요구 조건을 분리합니다',paragraph('용량은 모델이 들어갈 수 있는지, 대역폭은 얼마나 빨리 데이터를 공급하는지, 연산 상한은 공급된 데이터로 얼마나 빨리 계산하는지에 영향을 줍니다. 마지막으로 전력과 열 조건 안에서 지속적으로 동작할 수 있어야 합니다. 한 항목이 좋아져도 다른 항목에서 제한되면 전체 결과는 개선되지 않습니다.')+paragraph('아래 실험은 공급업체 가격표나 특정 GPU 설계가 아닙니다. 스택당 용량 24 GB, 고정 GPU 전력 200 W, 스택당 전력 8 W + 핀 속도 × 1.5 W, 전체 열저항 0.15 °C/W라는 가상 조건으로 비교합니다. 소비전력 모델은 제품 사양이 아닌 방향성 실험입니다.'))+
   '<div class="scenario-strip"><button class="preset" data-design="capacity">미션 A · 모델 용량</button><button class="preset" data-design="bandwidth">미션 B · 데이터 공급</button><button class="preset" data-design="thermal">미션 C · 열 제한</button></div>'+
   lab('26','세 가지 제약을 동시에 만족시키기',range('advs-dstacks','설계 HBM 스택 수',1,8,4,1,'개')+range('advs-dspeed','설계 핀 속도',2,12,6.4,.2,' Gbit/s')+range('advs-deff','설계 대역폭 이용률',30,95,75,5,'%')+range('advs-dcool','냉각 기준 온도',20,50,30,1,' °C')+result('advs-design-read'),'폭 1024 bit, 용량 24 GB/스택 가정. 전력·열·목표 수치는 비교 학습용입니다. 패키지 면적, 대역폭 공유, GPU별 실제 HBM 배치 제한은 포함하지 않습니다.','각 미션에서 스택 수·속도·이용률·냉각을 바꿔 모든 체크를 통과시키세요. 하나의 정답 설계만 있는 것은 아닙니다.')+
   '<div class="design-result" id="advs-design-checks" aria-live="polite"></div>'+
   lesson('결과를 보고서로 옮길 때',paragraph('“대역폭 부족”보다 “이 워크로드는 HBM byte 기준 집약도가 낮고, 지속 대역폭 목표를 달성하지 못했다”처럼 조건을 붙여 설명하세요. “12-Hi가 더 빠르다”보다 “용량 증가가 병목을 제거했는지, 인터페이스 속도도 바뀌었는지”를 나눠 봅니다.')+paragraph('사양표의 typical·maximum·minimum, operating range, test condition을 읽고, 측정 환경의 온도·전압·접근 패턴을 기록하세요. 실제 설계 의사결정에는 검증된 모델과 데이터시트, 담당 부서의 측정 자료가 필요합니다.'));
  const missions={capacity:{title:'미션 A · 144 GB 모델',capacity:144,bw:2.5,temp:85},bandwidth:{title:'미션 B · 4 TB/s 데이터 공급',capacity:96,bw:4,temp:90},thermal:{title:'미션 C · 온도 70 °C 이하',capacity:96,bw:2.5,temp:70}};let mission='capacity';
  function drawDesign(){const n=v('advs-dstacks'),s=v('advs-dspeed'),eff=v('advs-deff')/100,c=v('advs-dcool'),cap=n*24,bw=n*1024*s/8/1000*eff,p=200+n*(8+s*1.5),t=c+p*.15,m=missions[mission],ok=cap>=m.capacity&&bw>=m.bw&&t<=m.temp;read('advs-design-read',ok?'조건 달성 ✓':'설계 조정 중',`${m.title} · ${cap} GB / ${num(bw,3)} TB/s / ${num(t)} °C`);$('advs-design-checks').innerHTML=[['용량',cap>=m.capacity,`${cap} ≥ ${m.capacity} GB`],['유효 대역폭',bw>=m.bw,`${num(bw,3)} ≥ ${m.bw} TB/s`],['열 조건',t<=m.temp,`${num(t)} ≤ ${m.temp} °C`]].map(([k,pass,detail])=>`<div class="constraint ${pass?'pass':'fail'}"><span>${pass?'✓':'○'} ${k}</span><b>${detail}</b></div>`).join('');$('viz-26').innerHTML=svg(`<rect x="205" y="103" width="110" height="85" rx="8" fill="#ccf292" stroke="#08645b"/><text x="238" y="140">GPU</text><text x="218" y="168" class="label">200 W · 가정</text>`+Array.from({length:n},(_,i)=>{let x=i<4?37:361,y=25+(i%4)*61;return `<rect x="${x}" y="${y}" width="114" height="45" rx="5" fill="#85b6a4"/><text x="${x+11}" y="${y+28}">HBM ${i+1} · 24 GB</text><path d="M${i<4?151:361} ${y+22}L${i<4?205:315} 145" stroke="#9cbba6"/>`}).join('')+`<text x="55" y="300">전체 전력 ${num(p)} W · 단순 열 모델</text>`)}
  wire(['advs-dstacks','advs-dspeed','advs-deff','advs-dcool'],drawDesign);document.querySelectorAll('[data-design]').forEach(b=>b.onclick=()=>{mission=b.dataset.design;document.querySelectorAll('[data-design]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});drawDesign()});document.querySelector('[data-design="capacity"]').click();
  // Deepen the original foundations without changing their familiar experiments.
  const deeper={
   structure:['무엇을 쌓고, 무엇을 나란히 놓을까?', 'DRAM 다이는 수직으로 적층되지만, HBM 스택과 가속기는 보통 같은 패키지에서 나란히 배치됩니다. 그래서 HBM 스택은 3D 구조이고 전체 패키지는 2.5D 통합으로 설명될 수 있습니다. 동일한 “3D”라는 말이라도 셀 구조, 다이 적층, 시스템 패키징의 의미가 다를 수 있습니다.', '용량의 단위도 확인해야 합니다. 다이 밀도 24 Gb는 3 GB에 해당하므로 8개의 DRAM 다이가 모두 같은 밀도이면 산술 용량은 24 GB입니다. 여기서 스페어와 제품 구성의 상세는 제조사 사양을 따릅니다. Hi 수를 세는 범위에 베이스 다이를 포함하는지 설명을 함께 읽으세요.'],
   bandwidth:['세대 이름만으로 속도를 결정하지 않기','HBM3/3E는 1024 bit 인터페이스 계열이며 HBM4는 2048 bit 인터페이스로 확장됩니다. HBM3의 16개 64-bit 채널, HBM4의 32개 64-bit 채널은 전체 폭 안에서 나뉜 구성입니다. 채널과 의사채널 개수를 전체 폭 위에 다시 곱하면 중복 계산이 됩니다.','표준에서 정의한 인터페이스와 공급업체가 발표한 제품의 속도 등급은 다릅니다. 같은 HBM3E에서도 적층 수, 다이 밀도, 핀 전송률이 달라질 수 있습니다. 세대 비교는 속도·폭·용량·전력의 측정 조건을 같이 적어야 합니다.'],
   dram:['셀의 전하부터 로우 버퍼까지','셀 커패시터에 저장된 전하는 매우 작아 직접 큰 디지털 신호로 읽기 어렵습니다. ACT 후 작은 bitline 전압 차를 센스 앰프가 증폭하며 셀의 데이터를 복원합니다. 행을 여는 비용과 열린 행의 열을 선택하는 비용이 분리되는 이유입니다.','Row hit가 많으면 명령 오버헤드를 줄일 수 있지만, 특정 뱅크에 요청이 몰리면 병렬성이 부족해집니다. 컨트롤러는 행 지역성과 여러 뱅크의 동시 활용을 함께 고려합니다. 읽기와 쓰기 전환, activate 제한, refresh도 타이밍 예산에 영향을 줍니다.'],
   system:['Prefill과 decode의 데이터 이동을 나누어 보기','대규모 언어 모델의 prefill은 여러 입력 토큰을 함께 처리할 기회가 많고, decode는 다음 토큰을 순차적으로 생성하며 가중치·KV cache를 읽습니다. 배치 크기, 모델 구조, 커널 구현에 따라 병목이 달라지므로 “추론은 항상 메모리 병목”처럼 단정하지 않습니다.','모델 용량 계산에서는 가중치 이외의 항을 빠뜨리기 쉽습니다. KV cache는 시퀀스 길이·배치·attention 구조·정밀도의 영향을 받습니다. 학습에서는 gradient와 optimizer state도 필요하며, 모델 분할 시 통신 버퍼와 중간 데이터까지 고려해야 합니다.'],
   process:['접합 방법과 패키징 기술의 범위를 구분하기','마이크로범프는 미세 금속 연결 구조입니다. 하이브리드 본딩은 금속과 주변 절연층 접합을 함께 활용하는 방식으로 설명되며, 특정 제품이 어떤 방식을 쓰는지는 제품과 업체 자료를 확인해야 합니다. 모든 HBM 세대가 한 가지 접합 방식을 쓰는 것은 아닙니다.','CoWoS는 TSMC의 기술군입니다. 실리콘 인터포저, RDL 기반 구성, 로컬 실리콘 연결 등 구현 차이가 있을 수 있으므로 CoWoS를 단일 재료나 모든 HBM 패키지의 이름으로 쓰지 않습니다. 패키지 단면도에서 배선층·연결 위치·기판 경계를 먼저 읽어 보세요.'],
   thermal:['온도 하나보다 열 경로를 먼저 읽기','스택 내부 각 다이의 발열과 이웃 GPU의 발열이 결합될 수 있습니다. 열저항 숫자는 junction-to-ambient인지, junction-to-case인지, 어떤 경계 조건인지에 따라 뜻이 달라집니다. 열을 제거하는 경로를 모르면 같은 °C/W도 서로 비교하기 어렵습니다.','동적 전력은 스위칭 활동과 전압, 주파수의 영향을 받지만 실제 전체 전력에는 대기·리프레시·코어·I/O 등 여러 항이 있습니다. pJ/bit만 보고 총 전력을 확정하지 않습니다. 온도가 높아지면 refresh 조건이나 신뢰성 여유도 함께 점검해야 합니다.'],
   quality:['분모와 테스트 조건을 기록하기','수율은 웨이퍼, 개별 다이, 적층 스택, 최종 패키지마다 분모가 다릅니다. 좋은 다이로 시작해도 연결 결함과 조립 손실이 새로 발생할 수 있습니다. 단계별 수율을 단순히 곱할 때는 결함 독립성과 재작업·리페어 포함 여부를 확인합니다.','신뢰성 불량은 출하 시 기능 불량과 구분합니다. 온도와 전압 조건을 바꿔 재현되는지, 일시적 오류인지 반복되는지, 주소와 비트 위치가 고정되는지 기록하면 원인 가설을 좁히는 데 도움이 됩니다. 패턴만으로 물리 원인을 확정할 수는 없습니다.']
  };
  Object.entries(deeper).forEach(([id,[title,p1,p2]])=>{$('body-'+id).insertAdjacentHTML('afterbegin',lesson(title,paragraph(p1)+paragraph(p2)))});
  const worked={structure:'다이 밀도 24 Gb ÷ 8 = 다이당 3 GB. 8-Hi이면 3 × 8 = 24 GB, 12-Hi이면 3 × 12 = 36 GB. Hi 수 변경만으로 데이터 폭 1024 bit가 1536 bit가 되는 것은 아닙니다.',bandwidth:'1024 bit × 9.6 Gbit/s ÷ 8 = 1228.8 GB/s. 4개 스택이면 4915.2 GB/s, 이용률 75%이면 3686.4 GB/s = 3.6864 TB/s입니다.',dram:'예시 tRP=tRCD=읽기 지연=15 ns. 같은 행 hit는 15 ns, closed row는 30 ns, 다른 행 conflict는 45 ns. 전송 시간까지 포함한 전체 지연은 이 값과 다릅니다.',system:'70 billion 파라미터 × 2 byte = 140 GB. 기타 20 GB를 추가하면 160 GB이며, 80 GB 장치 2개는 용량 기준 하한입니다. 샤딩과 통신 비용이 사라지는 것은 아닙니다.',thermal:'냉각 기준 35 °C, 전력 12 W, 유효 열저항 2 °C/W이면 상승 24 °C, 단순 예측 온도 59 °C입니다. 기준 경계가 바뀌면 같은 열저항을 그대로 적용할 수 없습니다.',quality:'다이 99.5%, 접합 99%, 기타 패키징 98%, 8-Hi 독립 모델이면 0.995⁸ × 0.99⁸ × 0.98 ≈ 86.87%입니다. 선별 후 다이 확률을 웨이퍼 수율과 혼용하지 않습니다.'};
  Object.entries(worked).forEach(([id,text])=>{$('body-'+id).insertAdjacentHTML('beforeend',`<div class="worked-example"><b>계산을 따라가 보기</b>${text}</div>`)});
  $('intro').insertAdjacentHTML('afterend','<div class="learning-map"><p><b>처음이라면 01–08장, 패키징 업무라면 09–16장, 마지막은 설계 실험과 퀴즈.</b><br>이미 익숙한 장은 건너뛰고 필요한 실험부터 시작해도 됩니다.</p><a href="#channels">주소와 병렬성</a><a href="#dataflow">GPU 데이터 이동</a><a href="#signal">전기적 연결</a><a href="#testing">테스트와 리페어</a><a href="#design">종합 설계 미션</a></div>');
  $('body-bandwidth').insertAdjacentHTML('beforeend',`<div class="table-scroll"><table class="spec-table"><caption>인터페이스 비교 · 용량과 속도는 제품별 확인</caption><thead><tr><th>구분</th><th>총 데이터 폭</th><th>채널 / 의사채널</th><th>읽는 관점</th></tr></thead><tbody><tr><td>HBM3 / 3E</td><td>1024 bit</td><td>16 × 64 / 32 × 32 bit</td><td>같은 폭에서도 속도 등급이 다름</td></tr><tr><td>HBM4</td><td>2048 bit</td><td>32 × 64 / 64 × 32 bit</td><td>채널 수와 총 데이터 폭 증가</td></tr></tbody></table></div>`+source('https://www.synopsys.com/designware-ip/interface-ip/hbm/hbm4-phy.html','Synopsys · HBM4 PHY 구성')+source('https://www.micron.com/products/memory/hbm/hbm4','Micron · HBM4 제품 정보'));
  $('width').options[1].textContent='2048 bit · HBM4 폭 비교';
  $('body-structure').querySelector('.lab').insertAdjacentHTML('beforeend','<div class="layer-readout" id="advs-layer-note" aria-live="polite">도해의 DRAM 다이를 클릭하거나 키보드로 선택해 보세요. 각 층은 데이터를 저장하고 수직 TSV 경로로 연결됩니다.</div>');
  function chooseLayer(el){document.querySelectorAll('.layer-select.chosen').forEach(n=>n.classList.remove('chosen'));el.classList.add('chosen');$('advs-layer-note').textContent=`DRAM 다이 ${el.dataset.layer} 선택 · 다이마다 셀 어레이가 있으며 스택을 관통하는 수직 연결은 각 다이의 I/O를 베이스 쪽 연결로 이어 줍니다. 다이 번호는 이 그림의 아래쪽부터 세는 표시입니다.`}
  document.addEventListener('click',e=>{const el=e.target.closest('.layer-select');if(el)chooseLayer(el)});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.layer-select')){e.preventDefault();chooseLayer(e.target)}});
  const hero=$('hero-stack');
  hero.parentElement.insertAdjacentHTML('beforeend','<div class="hero-controls"><button id="advs-hero-explode" aria-pressed="true" disabled>적층 펼침 ✓</button><button id="advs-hero-turn" disabled>스택 확대 ↗</button><a href="#dataflow">데이터 경로 보기 →</a></div>');
  hero.addEventListener('hbm-hero-fallback',()=>{
   hero.dataset.heroMode='unavailable';hero.setAttribute('aria-busy','false');
   hero.innerHTML='<div class="pkg-hero-placeholder" role="status"><span>3D 모형을 불러올 수 없습니다.<br><a href="">페이지 다시 불러오기 ↻</a></span></div>';
   $('advs-hero-explode').disabled=true;$('advs-hero-turn').disabled=true;
  });
  setTimeout(()=>{if(hero.dataset.heroMode==='loading'){const message=hero.querySelector('.pkg-hero-loading-text');if(message)message.textContent='3D 모형을 불러오는 중입니다. 잠시만 기다려 주세요.'}},15000);
 }
 });
 window.HBMExtraQuestions=[
  ['HBM3의 16개 64-bit 채널을 합친 데이터 폭은?', ['1024 bit','16384 bit','64 bit'],0,'16 × 64 = 1024 bit입니다. 채널 수를 전체 버스 폭 위에 다시 곱하지 않습니다.'],
  ['같은 크기의 요청을 한 뱅크에 몰아 보내면?', ['뱅크가 늘었으므로 항상 동일한 성능','특정 뱅크에 대기가 누적될 수 있다','용량이 즉시 늘어난다'],1,'주소 매핑과 접근 분포가 병렬성을 좌우합니다. 뱅크 개수만으로 실제 활용도를 알 수 없습니다.'],
  ['버스트에서 쓸모 있는 데이터가 절반이면?', ['유용 데이터 대역폭도 줄 수 있다','핀 속도가 자동으로 2배가 된다','버스트 오버헤드가 항상 0이 된다'],0,'물리 전송량 중 실제 사용한 비율과 명령 오버헤드를 구분합니다.'],
  ['리프레시 실험의 tRFC / tREFI 비율은?', ['용량의 비율','단순한 뱅크 점유 시간 비율 예시','ECC 부호 길이'],1,'주기당 refresh 시간이 차지하는 비율입니다. 실제 병렬 refresh·세대별 정책은 더 복잡합니다.'],
  ['아이 다이어그램의 수평 닫힘을 증가시키는 변수는?', ['타이밍 지터','스택당 저장 용량만','KGD 분모'],0,'지터는 시간 축의 불확실성입니다. 노이즈·ISI 등도 눈의 열림과 해석에 영향을 줍니다.'],
  ['캐시 hit 100%인데도 첫 읽기에서 HBM 접근이 필요한 모델의 이유는?', ['고유 입력을 처음 가져와야 한다','계산식이 항상 틀리다','캐시가 비휘발성이기 때문이다'],0,'이 실험은 cold first access를 가정합니다. 이미 warm cache인 다른 조건과 구분하세요.'],
  ['데이터 패킷 경로에서 Controller와 PHY의 차이는?', ['둘 다 TSV의 이름','명령 스케줄링 제어와 전기 신호 인터페이스','둘 다 최종 검사 장비'],1,'컨트롤러는 명령과 주소 제어, PHY는 전기적 송수신 인터페이스를 담당합니다.'],
  ['SECDED의 기본 보장 범위는?', ['모든 bit 오류의 정정','1-bit 정정, 2-bit 검출','2-bit 정정, 3-bit 검출'],1,'확장 Hamming 예제의 보장입니다. 다중 오류는 범위 밖이고 실제 HBM ECC 구성은 별도입니다.'],
  ['Spare row 리페어 성공에 필요한 조건은?', ['모든 불량이 같은 물리 원인','불량 자원을 대체할 여분과 적절한 매핑','핀 속도 최대화'],1,'여분 개수, 결함 위치, 리페어 구조와 테스트 커버리지가 중요합니다.'],
  ['March 테스트가 접근 방향과 데이터를 바꾸는 이유는?', ['특정 fault model을 활성화하고 관찰하기 위해','파라미터 수를 늘리기 위해','열저항을 직접 측정하기 위해'],0,'관측 가능한 오류 유형이 테스트 순서와 데이터 패턴에 따라 달라집니다.'],
  ['불량 지도가 가장자리 집중을 보이면?', ['TSV 불량으로 바로 확정','공정·검사·취급 등의 가설을 추가 검증','ECC를 무조건 제거'],1,'공간 패턴은 원인 가설의 단서이며 확정적 인과 관계가 아닙니다.'],
  ['온도 변화에 따른 재료의 CTE 차이는?', ['항상 용량을 감소시킨다','휨·응력에 영향을 줄 수 있다','핀 속도를 정확히 예측한다'],1,'열팽창 차이는 기계적 변형의 요인입니다. 실제 변형은 층 구조와 경계조건의 영향도 받습니다.'],
  ['학습용 Weibull 그래프를 실제 사용수명 보증으로 쓸 수 있을까요?', ['시험 조건·표본 없이도 가능','불가능. 데이터와 가속 모델의 검증이 필요','반드시 10년 수명이다'],1,'가상 분포의 매개변수는 실제 제품 수명 데이터가 아닙니다.'],
  ['설계 미션에서 용량이 충분해도 성능이 부족할 수 있는 이유는?', ['용량·대역폭·열 조건은 각각 다른 제약','GB와 TB/s는 같은 단위','스택 수가 항상 무관'],0,'데이터가 들어가는 것과 빠르게 공급되는 것, 지속 작동 가능한 것은 분리된 요구입니다.']
 ];
})();
