'use strict';
const $=id=>document.getElementById(id),num=(v,d=1)=>Number(v).toLocaleString('ko-KR',{maximumFractionDigits:d});
const chapters=[
 ['structure','HBM의 구조','칩을 쌓는 것과 길을 넓히는 것','HBM(High Bandwidth Memory)은 여러 DRAM 다이를 수직으로 쌓고, 넓은 데이터 인터페이스로 가속기와 연결하는 메모리입니다. 적층은 용량과 밀도를, 인터페이스 폭과 핀 속도는 대역폭을 결정합니다.'],
 ['bandwidth','대역폭과 세대','한 번에 얼마나 많이 옮길까?','대역폭은 초당 전송 가능한 데이터의 양입니다. 지연시간은 요청부터 첫 데이터까지 걸리는 시간입니다. 도로의 차선 수가 늘어도 출발 신호를 기다리는 시간이 자동으로 줄지는 않습니다.'],
 ['dram','DRAM과 명령','데이터를 읽기 전에 해야 할 일','DRAM 셀은 트랜지스터와 커패시터로 비트를 저장합니다. 행을 열어 센스 앰프로 데이터를 복원한 뒤 열을 읽습니다. 같은 행을 재사용할 수 있는지에 따라 명령 순서가 달라집니다.'],
 ['system','AI와 메모리 병목','빠른 GPU도 데이터를 기다린다','연산 성능만으로 실행 속도를 설명할 수 없습니다. 연산 집약도(Arithmetic intensity)는 메모리에서 읽고 쓰는 1 byte당 수행하는 연산 수입니다. 대역폭과 곱하면 메모리가 공급할 수 있는 연산 속도를 얻습니다.'],
 ['process','TSV와 패키징','웨이퍼에서 하나의 패키지까지','TSV는 실리콘을 관통하는 수직 연결입니다. 다이 사이 접합과 인터포저 위 수평 연결은 역할이 다릅니다. 3D 적층 HBM과 가속기를 나란히 배치하는 2.5D 패키징을 구분해서 읽어 보세요.'],
 ['thermal','열과 전력','더 빠르게, 더 뜨겁게','스택 내부의 발열은 냉각 경로를 통해 빠져나갑니다. 열저항이 커지거나 소비전력이 증가하면 온도가 올라갑니다. 실제 제품은 다이별 발열과 열 결합을 포함한 상세 해석이 필요합니다.'],
 ['quality','수율과 신뢰성','좋은 다이도 연결이 나쁘면 실패한다','HBM은 다이, TSV, 접합, 패키징까지 여러 단계의 품질이 함께 작용합니다. KGD(Known Good Die) 선별은 불량 다이를 적층할 가능성을 낮추지만, 적층 이후 새로 생기는 결함을 없애지는 않습니다.'],
 ['practice','업무와 종합 퀴즈','이제 숫자를 설명할 차례','제품 사양을 읽을 때는 수치의 단위, 측정 조건, 기준 범위부터 확인하세요. 스택 하나인지 전체 가속기인지, 이론값인지 실측값인지가 다르면 같은 숫자도 의미가 달라집니다.']
];
const extensions=window.HBMExtensions||[];
chapters.push(...extensions.flatMap(ext=>ext.chapters));
const chapterOrder=['structure','bandwidth','dram','channels','transfers','refresh','system','dataflow','process','signal','thermal','mechanics','quality','testing','errors','failure','design','practice'];
chapters.sort((a,b)=>chapterOrder.indexOf(a[0])-chapterOrder.indexOf(b[0]));
const stored=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let completed=new Set(stored('hbm-complete',[]).filter(id=>chapters.some(c=>c[0]===id)));const save=()=>{try{localStorage.setItem('hbm-complete',JSON.stringify([...completed]))}catch{}};
$('nav').innerHTML=chapters.map(([id,title],i)=>`<a href="#${id}"><span>${String(i+1).padStart(2,'0')}</span>${title}</a>`).join('')+'<a href="#sources"><span>↗</span>참고 자료</a>';
$('chapters').innerHTML=chapters.map(([id,title,headline,intro],i)=>`<section class="chapter" id="${id}"><p class="eyebrow">CHAPTER ${String(i+1).padStart(2,'0')} / ${title}</p><h2>${headline}</h2><p>${intro}</p><div id="body-${id}"></div><button class="complete" data-complete="${id}">이 장 학습 완료 ✓</button></section>`).join('');
function updateProgress(){$('progress').max=chapters.length;$('progress').value=completed.size;$('progress-text').textContent=completed.size+' / '+chapters.length;document.querySelectorAll('[data-complete]').forEach(b=>{const done=completed.has(b.dataset.complete);b.classList.toggle('done',done);b.textContent=done?'학습 완료 · 다시 표시 취소':'이 장 학습 완료 ✓';b.setAttribute('aria-pressed',String(done))})}updateProgress();
document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{completed.has(b.dataset.complete)?completed.delete(b.dataset.complete):completed.add(b.dataset.complete);save();updateProgress()});$('reset-progress').onclick=()=>{completed.clear();save();updateProgress()};
if(stored('hbm-dark',false))document.body.classList.add('dark');$('theme').onclick=()=>{document.body.classList.toggle('dark');try{localStorage.setItem('hbm-dark',JSON.stringify(document.body.classList.contains('dark')))}catch{}};

const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))})},{rootMargin:'-15% 0px -65% 0px'});chapters.forEach(c=>obs.observe($(c[0])));
const svg=(body,view='0 0 520 320')=>`<svg xmlns="http://www.w3.org/2000/svg" role="${body.includes('role="button"')?'group':'img'}" aria-label="실험 결과 개념도" viewBox="${view}">${body}</svg>`;
function stack(n=8,gap=17,angle=0){let s='<ellipse cx="260" cy="280" rx="176" ry="21" fill="#c6d9cb" opacity=".4"/>';s+=`<g transform="translate(260 170) rotate(${angle}) translate(-260 -170)"><path d="M90 243 250 199 432 244 268 291Z" fill="#477968"/><path d="M90 243v13l178 48 164-47v-13l-164 47Z" fill="#315749"/><path d="M109 235 251 196 414 237 270 277Z" fill="#b6cbbb"/>`;for(let i=0;i<n;i++){let y=235-i*gap;s+=`<path class="layer-select" data-layer="${i+1}" role="button" tabindex="0" aria-label="DRAM 다이 ${i+1} 선택" d="M170 ${y} 255 ${y-24} 347 ${y} 262 ${y+24}Z" fill="${i===n-1?'#ccf292':'#85b6a4'}" stroke="#487b69"/><path d="M170 ${y}v7l92 24 85-24v-7l-85 24Z" fill="#3b7264"/>`;for(let j=0;j<5;j++)s+=`<circle class="packet" cx="${204+j*22}" cy="${y+1}" r="2.2" fill="#e8ffb9" style="animation-delay:${j*.2}s"/>`}s+='</g><text x="352" y="80" fill="#386959" font-size="13">DRAM 다이</text><text x="351" y="103" fill="#386959" font-size="12">수직 연결 · TSV</text><text x="47" y="282" fill="#386959" font-size="12">패키지 기판</text>';return svg(s,`0 ${Math.min(0,190-(n-1)*gap)} 520 ${320-Math.min(0,190-(n-1)*gap)}`)}
const cards=items=>`<div class="concepts">${items.map(([a,b])=>`<div class="concept"><b>${a}</b><p>${b}</p></div>`).join('')}</div>`;
const range=(id,label,min,max,value,step=1,unit='')=>`<label><span>${label}<output id="${id}-out" for="${id}">${value}${unit}</output></span><input id="${id}" aria-label="${label}" type="range" min="${min}" max="${max}" value="${value}" step="${step}" data-unit="${unit}"></label>`;
const select=(id,label,options)=>`<label>${label}<select id="${id}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;
const result=id=>`<div id="${id}" class="readout" role="status" aria-live="polite"></div>`;
const lab=(id,title,controls,note,task)=>`<div class="lab"><div class="lab-head"><small>EXPERIMENT ${id}</small><h3>${title}</h3></div><div class="lab-grid"><div class="controls">${controls}</div><div class="viz" id="viz-${id}"></div></div><p class="experiment-note">${note}</p><div class="task"><b>직접 해보기</b> ${task}</div></div>`;
function wire(ids,fn){ids.forEach(id=>{const el=$(id);el.addEventListener('input',()=>{const out=$(id+'-out');if(out)out.textContent=num(el.value,2)+el.dataset.unit;fn()})});fn()}
const v=id=>Number($(id).value),read=(id,value,desc)=>{$(id).innerHTML=`<strong>${value}</strong><p>${desc}</p>`};
const bars=(rows,max=0)=>{max=max||Math.max(...rows.map(r=>r[1]));return svg(rows.map(([name,value,color],i)=>`<text x="10" y="${38+i*68}" class="label">${name}</text><rect x="10" y="${48+i*68}" width="${Math.max(0,Math.min(380,380*value/max))}" height="22" rx="3" fill="${color||'#08645b'}"/><text x="${20+Math.min(380,380*value/max)}" y="${65+i*68}">${num(value,2)}</text>`).join(''),'0 0 520 '+(rows.length*68+25))};
$('body-structure').innerHTML=cards([['DRAM 다이','실제 데이터를 저장하는 층. 8-Hi, 12-Hi는 DRAM 다이의 적층 수를 뜻합니다.'],['베이스 다이','스택 아래의 연결과 제어 기능을 담당합니다. 세대와 설계마다 기능 범위가 다릅니다.'],['인터포저','HBM과 GPU 사이의 많은 신호를 수평으로 연결합니다. HBM 스택 내부의 TSV와 다릅니다.']])+lab('01','적층을 펼쳐 보세요',select('layers','DRAM 적층 수',[[4,'4-Hi'],[8,'8-Hi'],[12,'12-Hi']])+range('explode','층 사이 간격',9,25,17,1,'')+range('angle','모델 회전',-30,30,0,1,'°')+result('stack-read'),'비례가 생략된 SVG 구조 모델입니다. 간격 조작은 층을 관찰하기 위한 표시이며 실제 다이 간 거리 변경이 아닙니다.','8-Hi → 12-Hi로 바꿔 보세요. 인터페이스 속도가 같을 때 용량과 대역폭 중 무엇이 바뀔까요?');
wire(['layers','explode','angle'],()=>{$('viz-01').innerHTML=stack(v('layers'),v('explode'),v('angle'));read('stack-read',v('layers')*3+' GB','다이당 3 GB를 가정한 용량. 적층 수 자체로 버스 폭이 늘어나지는 않습니다.')});$('layers').value='8';$('layers').dispatchEvent(new Event('input'));
$('body-bandwidth').innerHTML=cards([['bit와 byte','8 bit = 1 byte. 핀 속도의 Gbit/s를 GB/s로 바꾸려면 8로 나눕니다.'],['1024개의 데이터 I/O','HBM3E의 데이터 인터페이스 예시. 주소·제어·전원 신호는 대역폭 계산의 데이터 폭에 넣지 않습니다.'],['이론값과 유효값','리프레시, 접근 패턴, 명령 오버헤드 등 때문에 실측 대역폭은 이론 상한보다 낮습니다.']])+lab('02','대역폭 계산기',select('width','데이터 버스 폭',[[1024,'1024 bit · HBM3/3E 예시'],[2048,'2048 bit · 넓은 인터페이스 비교']])+range('speed','핀당 전송률',2,12,9.6,.2,' Gbit/s')+range('stacks','HBM 스택 수',1,8,4,1,'개')+range('eff','대역폭 이용률',20,100,75,1,'%')+result('bw-read'),'전송률은 이미 핀당 초당 bit 수입니다. DDR이라는 이유로 여기에 다시 2를 곱하지 않습니다. 2048 bit 설정은 폭 비교용이며 다른 세대 제품의 보증 사양을 뜻하지 않습니다.','핀 속도를 유지하고 적층 수 대신 스택 수를 늘리면 전체 대역폭은 어떻게 변하나요?')+'<div class="formula">이론 GB/s = 데이터 폭(bit) × 핀 속도(Gbit/s) ÷ 8 × 스택 수<br>유효 GB/s = 이론 GB/s × 이용률</div><p class="small">제조사 예시: Micron HBM3E 12-Hi는 36 GB, 스택당 1.2 TB/s 초과로 소개됩니다. 본 계산기 기본값 9.6 Gbit/s × 1024 ÷ 8 = 1228.8 GB/s는 계산 예제입니다. TB/s는 1000 GB/s로 표시합니다.</p>';
wire(['width','speed','stacks','eff'],()=>{const b=v('width')*v('speed')/8;read('bw-read',num(b*v('stacks')*v('eff')/100/1000,3)+' TB/s',`스택 하나 ${num(b)} GB/s · 전체 이론 ${num(b*v('stacks')/1000,3)} TB/s`);$('viz-02').innerHTML=bars([['스택 하나 · GB/s',b],['전체 이론 · GB/s',b*v('stacks')],['전체 유효 · GB/s',b*v('stacks')*v('eff')/100,'#89b753']])});
$('body-dram').innerHTML=cards([['ACT · 행 열기','Wordline을 켜고 셀과 bitline 사이의 전하를 공유합니다. 센스 앰프가 작은 차이를 증폭하고 복원합니다.'],['RD / WR · 열 접근','열 주소에 해당하는 데이터를 읽거나 씁니다. 행이 이미 열려 있으면 ACT를 반복할 필요가 없습니다.'],['PRE / REF','PRE는 다음 행을 위해 뱅크를 준비합니다. REF는 시간이 지나 사라지는 전하를 주기적으로 복원합니다.']])+lab('03','로우 버퍼 접근 시간 비교',select('row','접근 상태',[['hit','Row hit · 같은 행'],['closed','Closed row · 열린 행 없음'],['conflict','Row conflict · 다른 행']])+range('trcd','tRCD · ACT→RD',10,25,15,1,' ns')+range('tcl','읽기 지연 · 단순 모델',10,25,15,1,' ns')+range('trp','tRP · PRE→ACT',10,25,15,1,' ns')+result('row-read'),'명령 대기만 보여주는 단순 예시입니다. 버스트 전송, 뱅크 간 병렬성, HBM 세대별 추가 타이밍 제약은 생략했습니다. 실제 타이밍은 데이터시트를 확인하세요.','Row hit와 conflict를 비교하세요. 핀 속도가 같아도 작은 랜덤 읽기의 성능이 다른 이유를 설명해 보세요.')+lab('04','뱅크를 나누면 대기가 줄어들까?',range('banks','독립 뱅크 수 · 예시',1,8,4,1,'개')+range('requests','같은 시각의 요청 수',1,16,8,1,'개')+select('pattern','주소 분포',[['spread','뱅크에 고르게 분산'],['hot','하나의 뱅크에 집중']])+result('bank-read'),'모든 요청은 처리 20 ns, 동일 시각 도착을 가정합니다. 실제 메모리 컨트롤러의 스케줄링과 공유 데이터 버스는 생략했습니다.','뱅크 수를 늘린 다음 주소를 한 곳에 집중시켜 보세요. 뱅크 수만 늘려도 빨라지나요?');
wire(['row','trcd','tcl','trp'],()=>{let seq=$('row').value==='hit'?[['RD',v('tcl')]]:$('row').value==='closed'?[['ACT',v('trcd')],['RD',v('tcl')]]:[['PRE',v('trp')],['ACT',v('trcd')],['RD',v('tcl')]];let total=seq.reduce((a,b)=>a+b[1],0),x=20;read('row-read',total+' ns','선택한 상태에서 첫 데이터까지의 단순 명령 지연');$('viz-03').innerHTML=svg('<text x="20" y="60">명령 타임라인</text>'+seq.map(([s,t],i)=>{let old=x,w=t*6;x+=w;return `<rect x="${old}" y="100" width="${w-2}" height="64" rx="4" fill="${['#89b753','#58a38d','#c4d4be'][i]}"/><text x="${old+10}" y="126">${s}</text><text x="${old+10}" y="151">${t} ns</text>`}).join('')+'<text x="20" y="205" class="label">명령 순서가 바뀌면 첫 데이터 도착 시간도 바뀝니다.</text>')});
wire(['banks','requests','pattern'],()=>{let n=v('banks'),q=v('requests'),hot=$('pattern').value==='hot',queues=Array.from({length:n},(_,i)=>hot?(i===0?q:0):Math.floor(q/n)+(i<q%n?1:0));read('bank-read',Math.max(...queues)*20+' ns','모든 요청을 완료하는 시간 · 요청당 처리 20 ns 가정');$('viz-04').innerHTML=svg(queues.map((count,i)=>`<text x="10" y="${27+i*33}" class="label">Bank ${i}</text>`+Array.from({length:count},(_,j)=>`<rect x="${90+j*24}" y="${12+i*33}" width="20" height="22" rx="3" fill="${j?'#a7c8b6':'#08645b'}"/>`).join('')).join(''))});
$('body-system').innerHTML=lab('05','Roofline: 메모리 한계와 연산 한계',range('roofbw','유효 메모리 대역폭',.2,8,1.2,.1,' TB/s')+range('compute','최대 연산 성능',20,400,100,10,' TFLOP/s')+range('ai','연산 집약도',1,200,20,1,' FLOP/byte')+result('roof-read'),'성능 상한 = min(최대 연산 성능, 대역폭 × 연산 집약도). TFLOP/s와 TB/s는 십진 단위입니다. 통신, 커널 효율, 정밀도 차이는 생략했습니다.','연산 집약도를 5로 낮춰 보세요. 연산 성능을 2배로 높이면 결과가 달라지나요?')+lab('06','모델이 HBM에 들어갈까?',range('params','모델 파라미터 수',1,200,70,1,' B')+select('bytes','파라미터당 저장 크기',[[2,'BF16/FP16 · 2 byte'],[1,'INT8 · 1 byte'],[.5,'INT4 · 0.5 byte']])+range('memory','가속기당 HBM 용량',16,192,80,8,' GB')+range('overhead','KV cache·활성값·기타 여유',0,100,20,1,' GB')+result('capacity-read'),'가중치 + 사용자가 지정한 기타 메모리만 계산하는 추론 용량 모델입니다. 학습 시 gradient, optimizer state 등을 별도로 계산해야 합니다. INT4 포장·스케일 메타데이터와 모델 분할 통신은 생략했습니다.','70B BF16 모델을 80 GB 가속기 하나에 넣을 수 있나요? 양자화와 가속기 수 증가의 차이를 생각해 보세요.');
wire(['roofbw','compute','ai'],()=>{let bw=v('roofbw'),p=v('compute'),a=v('ai'),perf=Math.min(p,bw*a),mem=bw*a<p;read('roof-read',num(perf)+' TFLOP/s',`${mem?'메모리 대역폭':'연산 성능'}이 상한 · 경계 집약도 ${num(p/bw)} FLOP/byte`);const x=t=>50+t/200*425,y=t=>260-t/400*210;$('viz-05').innerHTML=svg(`<path d="M50 40v220h425" fill="none" stroke="#8aaba0"/><text x="60" y="25" class="label">성능 TFLOP/s</text><text x="240" y="306" class="label">연산 집약도 FLOP/byte →</text><path d="M50 260 L${x(Math.min(200,p/bw))} ${y(Math.min(p,bw*200))} L475 ${y(Math.min(p,bw*200))}" fill="none" stroke="#08645b" stroke-width="4"/><circle cx="${x(a)}" cy="${y(perf)}" r="7" fill="#ba562c"/><text x="${Math.min(x(a)+12,370)}" y="${y(perf)-14}">${num(perf)} TFLOP/s</text><text x="12" y="260" class="label">0</text><text x="8" y="55" class="label">400</text><text x="451" y="282" class="label">200</text>`)});
wire(['params','bytes','memory','overhead'],()=>{let w=v('params')*v('bytes'),t=w+v('overhead'),n=Math.ceil(t/v('memory'));read('capacity-read',n+'개 이상',`가중치 ${num(w)} GB + 기타 ${v('overhead')} GB = ${num(t)} GB · 용량만 고려한 최소 가속기 수`);$('viz-06').innerHTML=bars([['가중치 · GB',w],['총 필요 · GB',t],['가속기 하나 · GB',v('memory'),'#89b753']])});
const processSteps=[['TSV 형성','실리콘 내부에 홀을 식각하고 절연막·배리어·금속을 형성합니다. TSV 직경, 깊이, 결함과 응력을 함께 관리합니다.'],['박막화·노출','웨이퍼 뒷면을 얇게 가공하고 TSV 연결부를 노출합니다. 얇은 다이는 취급, 휨, 크랙 관리가 중요합니다.'],['다이 선별','웨이퍼 테스트로 좋은 다이를 고릅니다. 테스트 커버리지와 검사 조건이 KGD 품질을 좌우합니다.'],['정렬·접합','다이를 정렬하고 연결합니다. 마이크로범프 기반 공정과 다른 접합 방식의 조건은 다르며 모든 HBM에 같은 방식을 적용하지 않습니다.'],['패키징','HBM과 가속기를 인터포저 등에 연결하고 기판에 실장합니다. CoWoS는 TSMC의 패키징 기술군이며 모든 HBM 패키지의 일반명은 아닙니다.'],['최종 검사','연결, 기능, 속도, 전력과 열 조건을 검증합니다. 시스템 단계의 안정성까지 확인해야 출하 품질을 판단할 수 있습니다.']];
$('body-process').innerHTML='<div class="lab"><div class="lab-head"><small>EXPERIMENT 07</small><h3>공정 흐름을 한 단계씩</h3></div><div class="steps">'+processSteps.map((s,i)=>`<button data-step="${i}">${i+1}. ${s[0]}</button>`).join('')+'</div><div class="lab-grid"><div class="step-info" id="step-info"></div><div class="viz" id="viz-07"></div></div><p class="experiment-note">대표 단계의 개념 흐름입니다. 업체별 via-first/middle/last, 순서, 접합 방식은 다를 수 있습니다.</p></div>'+lab('08','연결 정렬 오차 관찰',range('alignment','상대 정렬 오차',0,100,10,1,'%')+result('align-read'),'동일한 원형 패드의 기하학적 겹침만 계산합니다. 전기적 접속 저항과 실제 접합 수율은 재료·공정·온도·하중 등의 영향을 받습니다.','겹침 면적이 줄어드는 구간을 찾아 보세요. 겹침 50%가 수율 50%를 의미하나요?');
function packageDiagram(){return svg('<path d="M55 230 255 170 470 225 266 290Z" fill="#477968"/><path d="M80 207 255 156 448 207 269 260Z" fill="#c0d4bd"/><path d="M183 155 255 135 336 155 263 180Z" fill="#ccf292"/><path d="M183 155v44l80 25 73-23v-46l-73 25Z" fill="#497c68"/><text x="228" y="165">GPU</text>'+[110,350].map(x=>Array.from({length:5},(_,i)=>'<path d="M'+x+' '+(202-i*13)+' l40-12 45 13-40 12Z" fill="#85b6a4" stroke="#477968"/>').join('')).join('')+'<text x="50" y="65">HBM</text><path d="M80 74l62 60" stroke="#477968"/><text x="325" y="75">HBM</text><path d="M353 84l40 55" stroke="#477968"/><text x="50" y="302" class="label">3D 적층 HBM + GPU → 인터포저 위 2.5D 배치</text><text x="345" y="269" class="label">인터포저</text><path d="M355 255l-34-11" stroke="#477968"/>')}
function showStep(i){document.querySelectorAll('[data-step]').forEach(b=>{b.classList.toggle('selected',+b.dataset.step===i);b.setAttribute('aria-pressed',String(+b.dataset.step===i))});$('step-info').innerHTML=`<h3>${processSteps[i][0]}</h3><p>${processSteps[i][1]}</p><div class="task"><b>업무 질문</b> 이 단계에서 생긴 결함을 다음 단계에서 검출할 수 있을까요?</div>`;$('viz-07').innerHTML=i<3?svg(`<rect x="70" y="100" width="350" height="${i===1?45:100}" rx="4" fill="#9abaaa"/><text x="70" y="80">실리콘 웨이퍼 단면</text>`+Array.from({length:8},(_,j)=>`<rect x="${92+j*40}" y="95" width="10" height="${i===1?55:110}" fill="${i===2&&j===3?'#ba562c':'#d7a95b'}"/>`).join('')+`<text x="70" y="245" class="label">${i===2?'주황색: 선별에서 발견한 불량 예시':'금색: 수직 연결부 · 구조 개념도'}</text>`):i===4?packageDiagram():stack(i===3?4:8,15,0)}document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>showStep(+b.dataset.step));showStep(0);
wire(['alignment'],()=>{let d=v('alignment')/100*2,area=(2*Math.acos(d/2)-.5*d*Math.sqrt(4-d*d))/Math.PI*100;read('align-read',num(area)+'%','두 연결 패드의 기하학적 겹침 면적 · 전기적 합격 판정 아님');$('viz-08').innerHTML=svg(`<circle cx="210" cy="145" r="70" fill="#08645b" opacity=".7"/><circle cx="${210+d*70}" cy="145" r="70" fill="#d7a95b" opacity=".65"/><text x="140" y="250">아래 패드</text><text x="300" y="250">위 패드</text><path d="M210 145h${d*70}" stroke="#183c39" stroke-dasharray="4"/>`)});
$('body-thermal').innerHTML=lab('09','열저항과 온도 상승',range('ambient','냉각 기준 온도',20,65,35,1,' °C')+range('power','스택 소비전력',2,30,12,1,' W')+range('resistance','유효 열저항',.5,5,2,.1,' °C/W')+result('heat-read'),'T = 기준 온도 + 전력 × 유효 열저항. 냉각 기준은 단순한 주변/냉각 경계입니다. 특정 제품의 junction 온도 또는 허용 온도를 보증하지 않습니다.','전력을 2배로 늘린 경우와 열저항을 절반으로 줄인 경우를 비교해 보세요.')+lab('10','데이터 전송의 에너지',range('traffic','실제 전송량',100,2000,1000,50,' GB/s')+range('energy','전송 bit당 에너지',.5,8,2,.1,' pJ/bit')+result('energy-read'),'I/O 데이터 전송 에너지의 이상화 계산입니다. DRAM 코어, 리프레시, 대기 및 컨트롤러 전력은 제외하며 전체 HBM 소비전력과 같지 않습니다.','동일한 전송량에서 pJ/bit를 줄이면 무엇이 바뀌나요? 대역폭 이용률이 낮으면 전체 전력도 같은 비율로 줄까요?');
wire(['ambient','power','resistance'],()=>{let t=v('ambient')+v('power')*v('resistance');read('heat-read',num(t)+' °C',`기준 ${v('ambient')} °C + 상승 ${num(v('power')*v('resistance'))} °C`);$('viz-09').innerHTML=svg(`<defs><linearGradient id="heat" x2="0" y2="1"><stop stop-color="#c25935"/><stop offset="1" stop-color="#ccf292"/></linearGradient></defs><rect x="155" y="55" width="205" height="150" rx="6" fill="url(#heat)"/>`+Array.from({length:7},(_,i)=>`<path d="M155 ${75+i*18}h205" stroke="#f7f8f4"/>`).join('')+`<path d="M175 40v-25m80 25v-25m80 25v-25" stroke="#ba562c" stroke-width="3"/><rect x="120" y="220" width="275" height="25" rx="5" fill="#83b5a0"/><text x="145" y="283">냉각 경로 · 열저항 ${v('resistance')} °C/W</text>`)});
wire(['traffic','energy'],()=>{let p=v('traffic')*8*v('energy')/1000;read('energy-read',num(p,2)+' W','전송량 × 8 bit/byte × pJ/bit · I/O만의 예시');$('viz-10').innerHTML=bars([['현재 I/O 전력 · W',p],['에너지 절반일 때 · W',p/2,'#89b753']])});
$('body-quality').innerHTML=cards([['수율 · Yield','제조 투입 대비 합격 비율. 웨이퍼 수율, 스택 수율, 최종 패키지 수율은 분모가 다릅니다.'],['ECC와 리던던시','ECC는 특정 오류 패턴을 정정하며, 리던던시는 결함 자원을 여분으로 대체합니다. 모든 물리 결함을 고칠 수는 없습니다.'],['신뢰성 · Reliability','출하 시 합격과 사용 중 안정성은 다릅니다. 온도, 전압, 시간과 사용 패턴에 대한 시험 조건을 함께 확인합니다.']])+lab('11','적층 수율: 작은 손실의 누적',select('yieldlayers','DRAM 적층 수',[[4,'4-Hi'],[8,'8-Hi'],[12,'12-Hi'],[16,'16-Hi · 가상 비교']])+range('dieyield','선별 후 다이 합격 확률',90,100,99.5,.1,'%')+range('bondyield','접합 인터페이스 합격 확률',95,100,99,.1,'%')+range('packageyield','기타 패키징 합격 확률',90,100,98,.1,'%')+result('yield-read'),'독립 결함, 동일 확률, 재작업 없음 가정. 접합은 베이스 다이 포함 n개 인터페이스로 계산하며 베이스 다이 자체 수율은 기타 항에 포함합니다. 실제 KGD·리페어·상관 결함은 별도 분석이 필요합니다.','합격 확률 99%는 충분히 높아 보입니다. 적층 수를 늘리면 최종 수율은 어떻게 바뀌나요?')+'<div class="formula">스택 수율 = (선별 후 다이 합격 확률)^n × (접합 합격 확률)^n × 기타 패키징 합격 확률</div><div class="task"><b>불량 분석의 시작</b> 증상 재현 → 전압·온도·속도 조건 기록 → 위치/뱅크/비트 패턴 분류 → 물리·전기 분석 → 원인 가설 검증. 오류 개수만 보고 TSV 불량이라고 단정하지 않습니다.</div>';
wire(['yieldlayers','dieyield','bondyield','packageyield'],()=>{let n=v('yieldlayers'),d=(v('dieyield')/100)**n,b=(v('bondyield')/100)**n,p=v('packageyield')/100,y=d*b*p;read('yield-read',num(y*100,2)+'%',`1000개 투입 시 기대 합격 ${num(1000*y,0)}개 · 기대값이며 실제 정수 결과와 다름`);$('viz-11').innerHTML=bars([['다이 단계 누적 · %',d*100],['접합까지 누적 · %',d*b*100],['최종 · %',y*100,'#89b753']],100)});$('yieldlayers').value='8';$('yieldlayers').dispatchEvent(new Event('input'));
const questions=[['8-Hi에서 12-Hi로 바꾸고 I/O 폭과 핀 속도를 유지하면?', ['스택 대역폭이 자동으로 1.5배','다이당 용량이 같으면 스택 용량이 1.5배','지연시간이 자동으로 절반'],1,'적층 수는 우선 용량과 관련됩니다. 대역폭은 데이터 폭과 핀 전송률로 계산합니다.'],['1024 bit × 8 Gbit/s의 스택 이론 대역폭은?', ['1024 GB/s','8192 GB/s','64 GB/s'],0,'1024 × 8 ÷ 8 = 1024 GB/s. 핀 전송률에 DDR 계수를 다시 곱하지 않습니다.'],['Roofline에서 연산 집약도가 낮으면 먼저 확인할 것은?', ['GPU 연산 유닛 개수만','메모리 대역폭과 데이터 재사용','DRAM 적층 수만'],1,'낮은 집약도에서는 대역폭 × 집약도가 연산 성능보다 작아질 수 있습니다. 데이터 재사용으로 집약도를 높이는 방법도 있습니다.'],['KGD를 쓰면 적층 이후 테스트는?', ['생략해도 된다','접합과 적층 이후 발생 결함 검출에 필요하다','용량 확인만 하면 된다'],1,'KGD는 선별 전후 다이 품질을 개선하지만 접합과 패키징 중 생긴 불량은 최종 검사로 확인해야 합니다.'],['1.2 TB/s와 36 GB는 각각 무엇일까요?', ['대역폭과 용량','지연시간과 대역폭','소비전력과 용량'],0,'TB/s는 초당 전송량, GB는 저장량입니다. 어떤 스택/제품/조건의 수치인지도 확인하세요.'],['정렬 패드 겹침 50%이면 실제 접합 수율도 50%일까요?', ['항상 같다','아니다. 재료와 공정 조건을 검증해야 한다','항상 100%이다'],1,'기하학적 겹침은 관찰 변수 중 하나입니다. 전기 접속과 최종 수율은 추가 조건이 필요합니다.']];
questions.push(...(window.HBMExtraQuestions||[]));
const glossary=[['TSV','Through-Silicon Via. 실리콘을 관통하는 수직 전기 연결.'],['Interposer · 인터포저','여러 칩 사이를 연결하는 중간 배선 구조. 실리콘·RDL 등 구현 방식이 다릅니다.'],['Microbump · 마이크로범프','다이 사이를 연결하는 미세 접합 구조. 피치, 정렬, 접합 품질이 중요합니다.'],['KGD','Known Good Die. 정해진 검사 조건에서 양품으로 선별한 다이. 완전 무결함 보증과 같지 않습니다.'],['Bandwidth · 대역폭','단위 시간당 전송량. 이론 peak와 sustained 유효 대역폭을 구분합니다.'],['Latency · 지연시간','요청부터 응답까지 걸리는 시간. 어느 구간을 측정하는지 지정해야 합니다.'],['Channel / Bank','채널은 명령·데이터 경로의 구분, 뱅크는 DRAM 내부 독립 동작 단위입니다. 세대별 구성을 확인합니다.'],['Refresh · 리프레시','셀 전하를 유지하기 위한 주기적 복원. 타이밍·온도·정책에 따라 접근에 영향을 줍니다.'],['Warpage · 휨','온도·재료·두께 차이 등으로 구조가 휘는 현상. 정렬과 접합 품질에 영향을 줄 수 있습니다.'],['Thermal resistance · 열저항','전력 대비 온도 상승의 정도. °C/W 단위와 기준 경계를 함께 확인합니다.'],['ECC','Error-Correcting Code. 설계된 범위의 오류를 검출·정정하는 코드입니다.'],['CoWoS','Chip-on-Wafer-on-Substrate. TSMC 패키징 기술군의 이름이며 구성별 구현이 다릅니다.']];
glossary.push(...[["Pseudo-channel · 의사채널","채널을 더 작은 접근 경로로 나눈 구성. 전체 데이터 폭을 넘어서 추가 대역폭 배수로 계산하지 않습니다."],["DQ","실제 데이터를 송수신하는 신호. 주소·제어·전원 신호와 구분합니다."],["PHY","Physical layer. 컨트롤러와 핀 사이의 전기적 송수신·타이밍 인터페이스입니다."],["Memory controller","주소 해석, 명령 순서, 큐와 동작 타이밍을 관리하는 제어 기능입니다."],["Burst · 버스트","하나의 읽기/쓰기 명령에 이어 전송하는 데이터 묶음. 길이와 접근 단위는 세대와 모드에 따라 다릅니다."],["Outstanding requests","요청은 보냈지만 응답을 아직 받지 않은 동시 처리 요청. 충분한 수가 있어야 지연을 숨길 수 있습니다."],["Stride","연속 접근 주소 사이의 간격. 반복적인 주소 간격이 특정 채널·뱅크에 접근을 집중시킬 수 있습니다."],["tREFI / tRFC","Refresh interval과 refresh cycle time에 관한 타이밍. 정확한 명령 범위와 제품 조건을 확인해야 합니다."],["Retention · 유지","DRAM 셀이 데이터를 유지할 수 있는 특성. 온도·시간·셀별 편차와 VRT 등의 영향을 받습니다."],["UI · Unit interval","한 심볼을 전송하는 기준 시간. 아이 다이어그램의 수평축을 정규화하는 데 사용합니다."],["Jitter · 지터","전이 또는 샘플링 시점의 흔들림. 시간 여유를 줄이는 요인입니다."],["ISI","Inter-symbol interference. 이웃한 심볼과 채널의 응답이 겹쳐 현재 신호에 영향을 주는 현상입니다."],["BER","Bit error rate. 비교한 전체 bit 대비 오류 bit 비율. 시험 조건과 표본 규모를 함께 확인합니다."],["SECDED","Single-error correction, double-error detection. 실험은 확장 Hamming 예제이며 실제 HBM ECC 구현과 동일하지 않습니다."],["March test","메모리 위치를 방향과 읽기/쓰기 순서에 따라 검사하여 특정 fault model을 활성화·관찰하는 알고리즘 계열입니다."],["Stuck-at fault","셀 또는 신호가 특정 0/1 값에 고정되는 추상적인 결함 모델. 물리 원인 하나와 일대일로 같지 않습니다."],["Spare / Repair","여분 행·열 등의 자원으로 결함 자원을 대체하고 논리 주소를 다시 연결하는 기능입니다."],["On-die ECC / Host ECC","다이 내부 보호와 호스트·컨트롤러 쪽 보호는 구간과 가시성이 다릅니다. 정정 오류 지표의 기준을 확인합니다."],["CTE","Coefficient of thermal expansion. 온도 변화에 대한 열팽창 정도이며 재료 간 차이가 응력·변형에 영향을 줄 수 있습니다."],["Thermal cycling","온도를 반복 변화시키는 시험. 실제 사용 조건과 가속 조건 사이의 관계를 검증해야 합니다."],["Weibull distribution","수명·고장 확률 데이터를 표현하는 데 쓰이는 분포. shape와 scale은 데이터에 맞춰 추정해야 하며 가상 그래프가 수명 보증은 아닙니다."],["KV cache","Attention 연산의 key/value 중간 데이터를 저장하는 캐시. 토큰 수·배치·KV head·정밀도 등의 영향을 받습니다."],["Prefill / Decode","입력 토큰을 처리하는 단계와 다음 토큰을 생성하는 단계. 워크로드와 배치 조건에 따라 병목이 달라집니다."],["Arithmetic intensity","측정 계층에서 이동한 byte당 연산 수. FLOP/byte 단위와 byte를 집계한 계층을 같이 명시합니다."]]);
$('body-practice').innerHTML='<div class="task"><b>회의에서 확인할 5가지</b><br>① 스택당인가, 가속기 전체인가? ② GB와 Gb를 구분했는가? ③ 속도 등급과 온도 조건은? ④ 이론값인가, 실측값인가? ⑤ 불량률의 분모와 테스트 단계는?</div><h3>개념 점검 · 20문항</h3><p class="small">답을 선택하면 이유가 나옵니다. 정답을 맞혀도 다른 선택지의 의미를 설명해 보세요.</p><div id="quiz-score" class="readout" role="status">0 / 20 정답</div>'+questions.map((q,i)=>`<div class="quiz" id="quiz-${i}"><p>${i+1}. ${q[0]}</p>${q[1].map((a,j)=>`<button data-q="${i}" data-answer="${j}">${a}</button>`).join('')}<div class="feedback" id="feedback-${i}" aria-live="polite"></div></div>`).join('')+'<h3 style="margin-top:32px">업무 용어 카드</h3><div class="terms">'+glossary.map(([t,d])=>`<details><summary>${t}</summary><p>${d}</p></details>`).join('')+'</div>';
const answers={};document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{let i=+b.dataset.q,a=+b.dataset.answer,correct=a===questions[i][2];answers[i]=correct;document.querySelectorAll(`[data-q="${i}"]`).forEach(x=>{x.classList.remove('right','wrong');x.setAttribute('aria-pressed',String(x===b))});b.classList.add(correct?'right':'wrong');$('feedback-'+i).textContent=(correct?'정답입니다. ':'다시 생각해 보세요. ')+questions[i][3];$('quiz-score').textContent=Object.values(answers).filter(Boolean).length+' / '+questions.length+' 정답 · '+Object.keys(answers).length+'문항 응답'});

const extensionApi={$,num,cards,range,select,result,lab,wire,v,read,svg,bars,stack};
for(const ext of extensions)ext.init(extensionApi);
document.querySelectorAll('.lab-head small').forEach((el,i)=>el.textContent='EXPERIMENT '+String(i+1).padStart(2,'0'));
['12','15','18','19','20','21','23'].forEach(id=>$('viz-'+id).closest('.lab').classList.add('wide-lab'));
$('intro-count').textContent=chapters.length+'개 챕터';
$('experiment-count').textContent=document.querySelectorAll('.lab').length+'개 실험';
$('quiz-score').textContent='0 / '+questions.length+' 정답';
document.querySelector('#body-practice>h3').textContent='개념 점검 · '+questions.length+'문항';
